project:
  type: website
  output-dir: docs

website:
  title: "mmorenorolon.github.io"
  favicon: 
  navbar: Melannie Moreno Logo
    #logo: Melannie Moreno Logo.png
    #logo-alt: "the name Melannie Moreno"
    left:
    - href: index.qmd
      - text: Home
    - about.qmd
    - href: resources.qmd
      - text: Resources
      - icon: github
      - href: https://github.com/mmorenorolon/mmorenorolon.github.io
    page-footer:
    left: Copywright 2025, Melannie Moreno Rol√≥n
      right:
      - posts.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito



