project:
  type: website
  output-dir: docs

format:
  html:
    theme: [cosmo, brand]
    css: styles.css
    toc: true
    page-layout: full
    
website:
  title: "Melannie Moreno Rolón"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: posts.qmd
        text: Blog Posts
    right:
      - icon: github
        href: https://github.com/mmorenorolon/mmorenorolon.github.io
  page-footer:
    left: "Copyright 2025, Melannie Moreno Rolón"
    right:
      - href: posts.qmd
        text: Posts
